import { ClipboardCheck } from 'lucide-react'
import { useState } from 'react'
import { AppShell } from '../components/layout/AppShell'
import { Button } from '../components/ui/Button'
import { useAuth } from '../hooks/useAuth'
import { useCourseData } from '../hooks/useCourseData'
import { fetchDiagnostic, submitDiagnostic, type DiagnosticQuestion, type DiagnosticResult } from '../services/accountApi'

export function DiagnosticPage() {
  const { token, status } = useAuth(); const { skills } = useCourseData()
  const [questions, setQuestions] = useState<DiagnosticQuestion[]>([]); const [answers, setAnswers] = useState<Record<string,string>>({}); const [result, setResult] = useState<DiagnosticResult>(); const [message, setMessage] = useState('')
  async function start() { if (!token) return; try { setQuestions((await fetchDiagnostic(token)).questions); setResult(undefined); setMessage('') } catch (reason) { setMessage(reason instanceof Error ? reason.message : String(reason)) } }
  async function submit() { if (!token) return; try { setResult(await submitDiagnostic(token, answers)) } catch (reason) { setMessage(reason instanceof Error ? reason.message : String(reason)) } }
  return <AppShell><div className="mx-auto max-w-4xl px-4 py-10 sm:px-6 lg:px-8"><p className="eyebrow">Placement test</p><h1 className="mt-2 text-3xl font-black text-slate-950 dark:text-white">Python 能力诊断</h1><p className="mt-3 text-sm text-slate-500">诊断接口不会提前返回答案；提交后按技能生成得分和学习建议。</p>{status !== 'authenticated' ? <div className="mt-8 rounded-3xl border p-8 text-center text-sm text-slate-500">请先在“账号”页面登录后参加诊断。</div> : !questions.length ? <Button className="mt-8" onClick={start}><ClipboardCheck size={16} />开始 20 题诊断</Button> : result ? <div className="mt-8 rounded-3xl border bg-white p-7 dark:bg-white/[0.03]"><div className="text-4xl font-black text-emerald-600">{result.score}%</div><p className="mt-2 text-sm text-slate-500">答对 {result.correct}/{result.total}</p><h2 className="mt-6 font-bold">建议优先训练</h2><div className="mt-3 flex flex-wrap gap-2">{result.recommendedSkillIds.map((id) => <span key={id} className="rounded-full bg-rose-50 px-3 py-1 text-xs text-rose-600">{skills.find((skill) => skill.id === id)?.title ?? id}</span>)}</div><Button className="mt-6" variant="secondary" onClick={start}>重新诊断</Button></div> : <div className="mt-8 space-y-5">{questions.map((question,index) => <section key={question.id} className="rounded-3xl border bg-white p-6 dark:bg-white/[0.03]"><div className="text-xs font-bold text-emerald-600">{index+1}/{questions.length} · 难度 {question.difficulty}</div><h2 className="mt-2 font-bold text-slate-950 dark:text-white">{question.prompt}</h2><div className="mt-4 grid gap-2">{question.options.map((option) => <button key={option} onClick={() => setAnswers((current) => ({...current,[question.id]:option}))} className={`rounded-xl border p-3 text-left text-sm ${answers[question.id] === option ? 'border-emerald-400 bg-emerald-50 dark:bg-emerald-400/10' : ''}`}>{option}</button>)}</div></section>)}<Button onClick={submit} disabled={Object.keys(answers).length < questions.length}>提交诊断</Button></div>}{message && <p className="mt-4 text-sm text-rose-500">{message}</p>}</div></AppShell>
}
